title: Artemiy Volkov
baseurl: "http://citruscream.ru/rtmvlv" # the subpath of your site, e.g. /blog
url: "http://citruscream.ru/rtmvlv" # the base hostname & protocol for your site, e.g. http://example.com

permalink: none

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - dev
